#!/usr/bin/env ts-node

/**
 * Generate TypeScript Types Script
 * 
 * This script generates TypeScript type definitions from translation files
 * to enable type-safe translation keys throughout the application.
 */

import * as fs from 'fs';
import * as path from 'path';

interface TranslationStructure {
  [key: string]: string | TranslationStructure;
}

class TypeGenerator {
  private localesDir = path.join(__dirname, '../../packages/i18n/src/locales');
  private outputFile = path.join(__dirname, '../../packages/i18n/src/types/i18next.d.ts');
  private baseLanguage = 'en';

  async generate(): Promise<void> {
    console.log('🔧 Generating TypeScript types from translation files...\n');

    // Get all namespaces from base language
    const namespaces = this.getNamespaces();

    if (namespaces.length === 0) {
      console.error('❌ No translation namespaces found!');
      process.exit(1);
    }

    console.log(`📚 Found namespaces: ${namespaces.join(', ')}\n`);

    // Generate type definitions
    const typeDefinitions = this.generateTypeDefinitions(namespaces);

    // Ensure output directory exists
    const outputDir = path.dirname(this.outputFile);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write to file
    fs.writeFileSync(this.outputFile, typeDefinitions, 'utf-8');

    console.log(`✅ Types generated successfully at: ${path.relative(process.cwd(), this.outputFile)}\n`);
  }

  private getNamespaces(): string[] {
    const langDir = path.join(this.localesDir, this.baseLanguage);

    if (!fs.existsSync(langDir)) {
      return [];
    }

    return fs
      .readdirSync(langDir)
      .filter((file) => file.endsWith('.json'))
      .map((file) => path.basename(file, '.json'));
  }

  private generateTypeDefinitions(namespaces: string[]): string {
    const imports = namespaces
      .map((ns) => `import type ${ns}Translations from '../locales/${this.baseLanguage}/${ns}.json';`)
      .join('\n');

    const resourceTypes = namespaces
      .map((ns) => `    ${ns}: typeof ${ns}Translations;`)
      .join('\n');

    return `// Auto-generated type definitions for i18next
// Do not edit this file manually - it will be overwritten

import 'i18next';

// Import translation files
${imports}

declare module 'i18next' {
  interface CustomTypeOptions {
    // Set default namespace
    defaultNS: 'common';
    
    // Define resources type
    resources: {
${resourceTypes}
    };
    
    // Return type for t function
    returnNull: false;
    
    // Key separator
    keySeparator: '.';
    
    // Namespace separator
    nsSeparator: ':';
  }
}

// Export namespace types for convenience
export type TranslationKey<NS extends keyof CustomTypeOptions['resources']> = 
  keyof CustomTypeOptions['resources'][NS];

export type Namespace = keyof CustomTypeOptions['resources'];

// Helper type to get nested keys
export type NestedKeyOf<ObjectType extends object> = {
  [Key in keyof ObjectType & (string | number)]: ObjectType[Key] extends object
    ? \`\${Key}\` | \`\${Key}.\${NestedKeyOf<ObjectType[Key]>}\`
    : \`\${Key}\`;
}[keyof ObjectType & (string | number)];

// Type-safe translation key for a specific namespace
export type TypedTranslationKey<NS extends Namespace> = 
  NestedKeyOf<CustomTypeOptions['resources'][NS]>;

// Full translation key with namespace
export type FullTranslationKey = {
  [NS in Namespace]: \`\${NS}:\${TypedTranslationKey<NS>}\`;
}[Namespace];
`;
  }
}

// Run the generator
const generator = new TypeGenerator();
generator.generate().catch((error) => {
  console.error('❌ Type generation failed:', error);
  process.exit(1);
});