export * from './analytics';
export * from './boundaries';
export * from './business';
export * from './commission';
export * from './confirmation';
export * from './legalDocuments';
export * from './lockDurations';
export * from './marking';
export * from './markingFees';
export * from './metrics';
export * from './nigeriaAddress';
export * from './paymentTimings';
export * from './performance';
export * from './propertyManagement';
export * from './proximityRadius';
export * from './queue';
export * from './referralConstants';
export * from './reports';
export * from './rewardTiers';
export * from './timeSlots';
export * from './virtualAccount';
export { COMPANY, ACTIVE_AREAS, isAreaActive, MARKING, PAYMENTS, PLANS, REFERRALS, TENANTS, SERVICES, VERIFICATION, NG_BANKS, AMENITIES, } from "./business";
export type { ActiveArea } from "./business";
//# sourceMappingURL=index.d.ts.map