/**
 * Metrics Constants
 * Constants for business metrics, KPIs, and performance indicators
 * Location: backend/shared/src/constants/metrics.ts
 */

// Platform Commission Rates
export const COMMISSION_RATES = {
  PLATFORM_BASE_RATE: 0.2, // 20% of rent
  LISTING_AGENT_SHARE: 0.5, // 50% of platform commission
  SUB_AGENT_SHARE: 0.5, // 50% of listing agent's share
  NEWCONDO_MARKING_FEE: 25000, // NGN
  AGENT_MARKING_FEE: 20000, // NGN
  AGENT_MARKING_COMMISSION: 0.25, // 25% of marking fee
} as const;

// Payment Confirmation Periods
export const CONFIRMATION_PERIODS = {
  RENTER_CONFIRMATION_HOURS: 24,
  PROPERTY_OWNER_CONFIRMATION_DAYS: 3,
  MAX_CONFIRMATION_ATTEMPTS: 5,
  CONFIRMATION_REMINDER_HOURS: 12,
} as const;

// Marking Service Metrics
export const MARKING_SERVICE_METRICS = {
  MAX_TIME_SLOT_HOURS: 3,
  MAX_COMPLETION_DAYS: 3,
  INITIAL_PAYMENT_AMOUNT: 1000, // NGN sent after marking
  QUEUE_POSITION_TIMEOUT_MINUTES: 180, // 3 hours
  MIN_AGENT_RELIABILITY_SCORE: 3.0,
} as const;

// Property Listing Metrics
export const PROPERTY_METRICS = {
  MIN_LISTING_DURATION_DAYS: 30,
  MAX_LISTING_DURATION_DAYS: 365,
  FEATURED_LISTING_DURATION_DAYS: 7,
  MAX_PROPERTY_IMAGES: 20,
  MAX_IMAGE_SIZE_MB: 10,
  MIN_PROPERTY_DESCRIPTION_LENGTH: 50,
  MAX_PROPERTY_DESCRIPTION_LENGTH: 2000,
} as const;

// User Verification Metrics
export const VERIFICATION_METRICS = {
  MAX_VERIFICATION_ATTEMPTS: 3,
  VERIFICATION_REVIEW_HOURS: 48,
  ID_DOCUMENT_VALID_MONTHS: 12,
  SELFIE_MATCH_THRESHOLD: 0.85,
  AUTO_VERIFICATION_THRESHOLD: 0.95,
} as const;

// Payment Metrics
export const PAYMENT_METRICS = {
  MIN_RENT_AMOUNT: 10000, // NGN
  MAX_RENT_AMOUNT: 10000000, // NGN
  PAYMENT_TIMEOUT_MINUTES: 15,
  REFUND_PROCESSING_DAYS: 7,
  VIRTUAL_ACCOUNT_MIN_BALANCE: 0,
  WITHDRAWAL_MIN_AMOUNT: 5000, // NGN
  FLUTTERWAVE_TRANSACTION_FEE_RATE: 0.014, // 1.4%
  FLUTTERWAVE_TRANSACTION_FEE_CAP: 2000, // NGN
} as const;

// Performance Thresholds
export const PERFORMANCE_THRESHOLDS = {
  // Agent Performance
  EXCELLENT_AGENT_RATING: 4.5,
  GOOD_AGENT_RATING: 3.5,
  POOR_AGENT_RATING: 2.5,
  MIN_AGENT_COMPLETION_RATE: 0.8, // 80%
  
  // Property Performance
  HIGH_DEMAND_VIEWS_PER_DAY: 50,
  AVERAGE_DEMAND_VIEWS_PER_DAY: 20,
  LOW_DEMAND_VIEWS_PER_DAY: 5,
  OPTIMAL_TIME_TO_RENT_DAYS: 14,
  
  // Platform Performance
  TARGET_CONVERSION_RATE: 0.15, // 15%
  MIN_ACCEPTABLE_CONVERSION_RATE: 0.05, // 5%
  TARGET_RETENTION_RATE: 0.8, // 80%
  MAX_ACCEPTABLE_CHURN_RATE: 0.25, // 25%
  
  // Payment Performance
  TARGET_PAYMENT_SUCCESS_RATE: 0.95, // 95%
  MIN_PAYMENT_SUCCESS_RATE: 0.85, // 85%
  MAX_REFUND_RATE: 0.05, // 5%
} as const;

// Growth Targets
export const GROWTH_TARGETS = {
  MONTHLY_USER_GROWTH_RATE: 0.15, // 15% per month
  MONTHLY_REVENUE_GROWTH_RATE: 0.2, // 20% per month
  QUARTERLY_LISTING_GROWTH_RATE: 0.25, // 25% per quarter
  YEARLY_MARKET_SHARE_TARGET: 0.1, // 10% market share
} as const;

// Revenue Metrics
export const REVENUE_METRICS = {
  TARGET_MONTHLY_REVENUE: 5000000, // NGN
  TARGET_QUARTERLY_REVENUE: 15000000, // NGN
  TARGET_ANNUAL_REVENUE: 60000000, // NGN
  PREMIUM_SUBSCRIPTION_MONTHLY: 5000, // NGN
  PREMIUM_SUBSCRIPTION_ANNUAL: 50000, // NGN
} as const;

// User Engagement Metrics
export const ENGAGEMENT_METRICS = {
  ACTIVE_USER_MIN_SESSIONS_PER_MONTH: 4,
  TARGET_AVERAGE_SESSION_DURATION_MINUTES: 15,
  TARGET_PAGES_PER_SESSION: 5,
  MAX_ACCEPTABLE_BOUNCE_RATE: 0.5, // 50%
  TARGET_RETURN_USER_RATE: 0.6, // 60%
} as const;

// Operational Metrics
export const OPERATIONAL_METRICS = {
  MAX_RESPONSE_TIME_MS: 200,
  TARGET_UPTIME_PERCENTAGE: 99.9,
  MAX_ERROR_RATE: 0.01, // 1%
  MAX_SUPPORT_TICKET_RESOLUTION_HOURS: 48,
  TARGET_FIRST_RESPONSE_MINUTES: 30,
} as const;

// Property Quality Scores
export const QUALITY_SCORES = {
  COMPLETE_PROFILE_POINTS: 100,
  VERIFIED_OWNER_BONUS: 20,
  HIGH_QUALITY_IMAGES_BONUS: 15,
  DETAILED_DESCRIPTION_BONUS: 10,
  LEGAL_DOCUMENTS_BONUS: 15,
  RECENT_UPDATE_BONUS: 5,
  MIN_QUALITY_SCORE_FOR_FEATURED: 80,
} as const;

// Agent Quality Metrics
export const AGENT_QUALITY_METRICS = {
  MIN_LISTINGS_FOR_RATING: 5,
  MIN_COMPLETIONS_FOR_RELIABILITY: 10,
  RESPONSE_TIME_TARGET_HOURS: 2,
  COMPLETION_TIME_TARGET_HOURS: 48,
  MAX_CANCELLATION_RATE: 0.1, // 10%
} as const;

// Referral Program Metrics
export const REFERRAL_METRICS = {
  REFERRER_BONUS_AMOUNT: 5000, // NGN
  REFEREE_DISCOUNT_PERCENTAGE: 0.1, // 10%
  MIN_REFERRAL_QUALIFICATION_DAYS: 30,
  MAX_REFERRAL_BONUS_PER_USER: 50000, // NGN
  REFERRAL_TIER_1_BONUS: 5000, // 1-5 referrals
  REFERRAL_TIER_2_BONUS: 7500, // 6-10 referrals
  REFERRAL_TIER_3_BONUS: 10000, // 11+ referrals
} as const;

// Security Metrics
export const SECURITY_METRICS = {
  MAX_LOGIN_ATTEMPTS: 5,
  ACCOUNT_LOCKOUT_DURATION_MINUTES: 30,
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_EXPIRY_DAYS: 90,
  OTP_EXPIRY_MINUTES: 10,
  OTP_MAX_ATTEMPTS: 3,
  SESSION_TIMEOUT_MINUTES: 60,
  REFRESH_TOKEN_EXPIRY_DAYS: 30,
} as const;

// Data Retention Metrics
export const DATA_RETENTION_METRICS = {
  EVENT_LOG_RETENTION_DAYS: 90,
  PAYMENT_LOG_RETENTION_YEARS: 7,
  USER_ACTIVITY_RETENTION_DAYS: 365,
  DELETED_USER_DATA_RETENTION_DAYS: 30,
  BACKUP_RETENTION_DAYS: 30,
} as const;

// Notification Metrics
export const NOTIFICATION_METRICS = {
  MAX_DAILY_NOTIFICATIONS_PER_USER: 10,
  MAX_WEEKLY_MARKETING_EMAILS: 2,
  EMAIL_OPEN_RATE_TARGET: 0.25, // 25%
  SMS_DELIVERY_RATE_TARGET: 0.98, // 98%
  PUSH_NOTIFICATION_CTR_TARGET: 0.1, // 10%
} as const;

// Location-Based Metrics
export const LOCATION_METRICS = {
  MAX_SERVICE_RADIUS_KM: 50,
  NEARBY_PROPERTIES_RADIUS_KM: 5,
  AGENT_ASSIGNMENT_RADIUS_KM: 20,
  MARKING_PRIORITY_RADIUS_KM: 10,
} as const;

// File Upload Metrics
export const UPLOAD_METRICS = {
  MAX_FILE_SIZE_MB: 10,
  MAX_FILES_PER_UPLOAD: 20,
  ALLOWED_IMAGE_FORMATS: ['jpg', 'jpeg', 'png', 'webp'],
  ALLOWED_DOCUMENT_FORMATS: ['pdf', 'doc', 'docx'],
  IMAGE_COMPRESSION_QUALITY: 0.85,
  THUMBNAIL_SIZE_PX: 300,
} as const;

// Rate Limiting Metrics
export const RATE_LIMITS = {
  API_REQUESTS_PER_MINUTE: 60,
  API_REQUESTS_PER_HOUR: 1000,
  LOGIN_ATTEMPTS_PER_HOUR: 5,
  PASSWORD_RESET_PER_DAY: 3,
  PROPERTY_CREATION_PER_DAY: 10,
  SEARCH_QUERIES_PER_MINUTE: 20,
} as const;

// Cache Metrics
export const CACHE_METRICS = {
  PROPERTY_LISTING_TTL_MINUTES: 15,
  USER_PROFILE_TTL_MINUTES: 30,
  ANALYTICS_DATA_TTL_MINUTES: 5,
  SEARCH_RESULTS_TTL_MINUTES: 10,
  STATIC_CONTENT_TTL_HOURS: 24,
} as const;

// Search and Filter Metrics
export const SEARCH_METRICS = {
  MAX_SEARCH_RESULTS: 100,
  DEFAULT_SEARCH_RESULTS: 20,
  MIN_SEARCH_QUERY_LENGTH: 3,
  MAX_PRICE_FILTER_RANGE: 10000000, // NGN
  MAX_BEDROOMS_FILTER: 10,
  AUTOCOMPLETE_MIN_CHARACTERS: 2,
  AUTOCOMPLETE_MAX_RESULTS: 10,
} as const;

// Business Health Indicators
export const HEALTH_INDICATORS = {
  CRITICAL_ERROR_THRESHOLD: 10, // errors per hour
  HIGH_RESPONSE_TIME_MS: 500,
  LOW_AVAILABILITY_THRESHOLD: 0.95, // 95%
  DATABASE_CONNECTION_POOL_MIN: 10,
  DATABASE_CONNECTION_POOL_MAX: 50,
  QUEUE_SIZE_WARNING_THRESHOLD: 1000,
  MEMORY_USAGE_WARNING_PERCENTAGE: 0.8, // 80%
} as const;

// A/B Testing Metrics
export const AB_TEST_METRICS = {
  MIN_SAMPLE_SIZE: 100,
  CONFIDENCE_LEVEL: 0.95,
  MIN_TEST_DURATION_DAYS: 7,
  MAX_TEST_DURATION_DAYS: 30,
  SIGNIFICANCE_THRESHOLD: 0.05,
} as const;

export default {
  COMMISSION_RATES,
  CONFIRMATION_PERIODS,
  MARKING_SERVICE_METRICS,
  PROPERTY_METRICS,
  VERIFICATION_METRICS,
  PAYMENT_METRICS,
  PERFORMANCE_THRESHOLDS,
  GROWTH_TARGETS,
  REVENUE_METRICS,
  ENGAGEMENT_METRICS,
  OPERATIONAL_METRICS,
  QUALITY_SCORES,
  AGENT_QUALITY_METRICS,
  REFERRAL_METRICS,
  SECURITY_METRICS,
  DATA_RETENTION_METRICS,
  NOTIFICATION_METRICS,
  LOCATION_METRICS,
  UPLOAD_METRICS,
  RATE_LIMITS,
  CACHE_METRICS,
  SEARCH_METRICS,
  HEALTH_INDICATORS,
  AB_TEST_METRICS,
};